:PROPERTIES:
:ID:       69519f3d-e371-4d4d-82fd-881124a1e062
:END:
#+title: shibou riyu

お伝えしたい動機は、２つあります。それは 1.「貴社での働き方に賛同した」ことと、2.「従業員の方々が、自分の仕事に自信を持っているように思え」ことです。
* 貴社での働き方に賛同した
 私が貴社に身を置きたい理由は仕事への姿勢のシンプルさに賛同したことです。私はその働き方を支えるのがユニケージ開発手法だと思っています。貴社で行われているインターンシップを４回参加し、ユニケージ開発手法とは「自由」を獲得する手段であり、道しるべだということを確信いたしました。
 その「自由」とは大きく分けて２つあります。ひとつは時間的な自由、もうひとつは仕事のコントロールの自由さです。たとえば、貴社は従業員に、仕事を早く終わらせることと、システム全体の構造を理解することを求めます。そしてそれを、コマンドの作成をはじめとした、さまざまな方法で実現する手段を作成、吟味し「自由」を加速させます。  「仕事を早く終わらせ、システムの理解が深くなる」ということ自体は、もちろん他の企業の従業員がその企業の方法論を用いたとしてもできることです。しかし多くの場合、複雑に問題に取り組んだゆえに、そのノウハウ自体も複雑になるという結果がともなうことになるでしょう。
 多くの企業は、手段の制約により問題を必要以上に大きくしているといえます。そういった複雑性がないシンプルな問題の方は解決のノウハウもシンプルになります。たとえば、コードの長さが複雑さの目安だとします。そして同じシステムでも他社のコードの長さは貴社より多くなりがちなことが言えると思います。それゆえ他社のシステムの扱いの複雑性が高くなるのは明らかです。またそうした条件では余計な複雑性をもっているのプロダクトを作っているともいえます。
 ユニケージ開発手法においては、解決のためのノウハウがシンプルであるがゆえに共有されやすいです。つまり、仕事やその理解を高速化する方法が、多くの従業員に気づかれやすくデザインされいているということです。それゆえ私は、ユニケージ開発手法とは「自由」を得るための一本の道しるべになっていると思います。
  以上が私がユニケージ開発手法に見た「自由」についてです。しかしユニケージ手法は何も、上の例のようなコードを書くことだけでなく、お米や味噌、野菜を栽培から調理まで行うということにも根ざしており、また配膳の当番をいかにチームで行うか、社員旅行でいかなるプランを立てるか、ということも含まれます。それらはシステムとして互いの類型になるように行われ、そのシンプルな行いから得た知恵によって仕事への姿勢を洗練していくのだと考えます。そして私はそれを美しいと考えていて、その輪のうちに入りたいと考え、貴社を志望しております。
 
* 従業員の方々が、自分の仕事に自信を持っているように思える
 以上で述べた「自由を得る」ことが根ざしている確証が持てるような従業員、あるいは関係者の方々の言葉も私の気持ちを貴社にむける大きなきっかけとなりました。たとえば、インターンでメンターの方々が、注意深く参加者の進捗を観察していたことは、貴社の理念に賛同している証拠で、自信に裏打ちされた行動だと思います。他には、もともと貴社に在籍していた、上田隆一さんが貴社を「古巣」と親しみをこめて呼んでいたことからも、愛されている組織なのだとわかります。
