:PROPERTIES:
:ID:       3ca9d85f-2893-4c89-a00c-cacc5f1fed72
:END:
#+title: wiki as graph

* グラフビューでナレッジを残すうれしさ
現在私が最も嬉しいと思う点をいくつか挙げます。
1. 素敵な気持になれる
   どんな仕事であろうが、成果物をいかにたくさん早く残せればよく、そのために過程を追求することが必要です。ですが、思うように結果が残せなかったりすることで精神的な余裕を失って、過程のクオリティを追求することをなおざりにするということをしてしまうことはあるとおもいます。これは最悪の状況ともいえますが案外時間に追われていたり、なんらかのプレッシャーがかかれば、余程屈強な精神をもっている人でなければは陥りがちな罠だといえます。
   それをさけるためには、小さい嬉しさを積み重ねる必要があります。とはいえそうした方法は人それぞれ異ります。例は様々挙げられるとはおもいますが、私個人の体験から、「何か表情をもったものを育てる」というのはアリなのではないかと思います。それは 盆栽やメダカ、Emacs などでもいいかもしれません。
   グラフビューというのはある種の表情があるとおもいます。ノードの数が増えてくると、ナレッジが花火のような見た目になってくるというのは、ある種の植物を育てているような感覚を得ることができるものです。そうしたものに水をあたえて大きくすることはなんと有意義で豊かなものか！と思っておくことで素敵な気持になれるはずです。

2. ナレッジのバランスがよくなる
   たとえば、ある日突然、「デザインパターンについて学ばなければならない！」といった強迫観念に囚われたとします。それは構文木を扱っていて、Visitor のオブジェクトをみたときに、「そういえば他のパターンにどんなパターンがあったか」や、「そもそも GOF のパターンだけがすべてじゃない」だとか、余計なことを考えはじめたときに表れるものかもしれません。こうしたことは、事前に手をうっておけばよいのです。つまり、Visitor に遭えば、Visitor を切り、State に遭えば、State を切る。そうして幾つかナレッジがたまれば、小さい花ができあがります。そしてそれを大いにさかせようとすることは気持の自然な流れであって、それは知識の偏りをなくすことでもあるということです。
