:PROPERTIES:
:ID:       f08c3ac5-f78b-462f-a369-f4a709bb762f
:END:
#+title: jiko PR
 
* 私についての概要
　私を一言で表すと、「苦行とうまくつきあう努力をする人間」です。これは、好きなことを嫌いにならないようにうまく、自分のやるべきことをスイッチする能力を磨いた末に行き着いた人格だと思います。その芽生えは中学生から続けている音楽がきっかけです。
　中学生になった時、音楽を本気でやろうと決め、独学で 5 年ほど続けていました。Youtube で自分より上手い年下の子供やベテランの方々の演奏をみて、自信を失いつつも、より多くの練習を闇雲に行っていました。その後アルバイトをしてお金を貯め、レッスンを受けるようになると、基礎の重要性と、それが理解できるまでの地道な練習の必要に気づきました。
　そうなってからは、ありえる全ての基礎的なものを探すことに心がけました。それらの中から自分が現在必要なものをいくつか取り出して、やりたい順番で行うようにしました。そうすると、多くのやるべきことの選択肢を知らない場合よりも、自分の今行っている、他人から見るとすごそうに見えないシンプルなことに、思いをこめて、楽しく打ち込めるようになりました。そして現在は吟味と積み重ねがすごいことを形作ることの確証を持っています(この点において、[[id:69519f3d-e371-4d4d-82fd-881124a1e062][shibou riyu]]における、貴社の働きかたのシンプルさに賛同し、マッチしたと考えています)。
 
* 大学での学び
　私は立教大学という大学の「文学部キリスト教学科」に在籍していて、キリスト教について、聖書の時代の時代背景、どういった順番で聖書が編纂されたのか、といった歴史や思想史などの基礎を学びました。ですが、私の興味の中心はキリスト教というよりかは、プリミティブな形の儀礼一般で、ゼミでは儀礼研究の理論を用いて、儀礼を分析していました。具体的には「乾杯」という行為を儀礼として分析するなどしていました。
 
* IT 系の仕事の経験、知識
　高校生ぐらいの時に一度プログラムを書いてみようとしていましたが、挫折し、大学 2 年生の夏ごろから本腰を入れて勉強し始めました。1年ほどして株式会社パレアナという会社で給料をもらいつつタスクをこなしていました。主に React　Native とというフレームワークを使ってスマホアプリの改修や作成の一部を行っていました。その他シェルスクリプトで小さいツールを書いて納品したりしていました。また、2022 年の 9 月には GLOBAL WALKERS という会社で、駐車場の監視カメラの AI の学習データとして、フェイクのナンバープレートの画像をつけてデータ量を増やすための、ナンバープレートを生成するツールを作って納品したことがあります。I
 
https://github.com/chiple?tab=repositories（Githubリポジトリ）
https://chiple.github.io/homepagr/（私のナレッジ置き場として作ったホームページです）
 
